Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@II2u7et 
StephenGrider
/
DockerCasts
52
5931k
Code
Issues
6
Pull requests
2
Actions
Projects
Wiki
Security
Insights
DockerCasts/complex/skaffold.yaml
@StephenGrider
StephenGrider skaffold
Latest commit 13d07ff on Mar 11
 History
 1 contributor
34 lines (34 sloc)  789 Bytes
  
apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: phhogphuc/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
    - image: phhogphuc/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
    - image: phhogphuc/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/client-cluster-ip-service.yaml