apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issueRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: toodyssey.com
  dnsNames:
    - toodyssey.com
    - www.toodyssey.com
  acme:
    config:
      - http01:
        ingressClass: nginx
      domains:
        - toodyssey.com
        - www.toodyssey.com